### ISSUE TITLE
Error after modifying for the first time the watched elements

### ISSUE THREAD

**Issue by micnic** [steelbrain/node-fswatcher#4]
Error after modifying for the first time the watched elements

```
$ node test.js
C:\Users\micnic\node_modules\node-fswatcher\Built\NativeWatcher.js:62
            return Self.Publish(OldStats.isDirectory() ? ["unlinkDir"] : ["unl
                                        ^
TypeError: Cannot read property 'isDirectory' of null
    at C:\Users\micnic\node_modules\node-fswatcher\Built\NativeWatcher.js:62:41
    at FSReqWrap.oncomplete (fs.js:99:15)
```

There, at `line 62 in NativeWatcher.js`, should be also a check for `OldStats`

**Comment by steelbrain** [comment]
Rewrite planned. Gonna fix shortly, thanks for the bug report
